### ISSUE TITLE
[BE] 백엔드 초기 진행상황

### ISSUE THREAD

**Issue by General-code** [codestates-seb/seb39_main_022#4]
- [x] ERD 설계
- [x] 테이블 정의서 
- [x] OPEN API 통신 자바 환경에서 하기
- [x] JWT를 Spring Security 없이 구현하여 DB에 토큰 정보 저장(mysql에 저장가능 -> redis에 저장되게끔 변경 여부 판단)
- [x] 첨삭 후 잘못된 이름 수정 (fcltyNm->fcltyName) (-이것도 명시성이 떨어짐 facultyName으로 해야 맞을 것 같다.-)
- [x] 잘못된 타입도 수정(특히 timezone과 관련된 시간) [TimeStamp를 왜 써야 하는가](https://blog.gangnamunni.com/post/mysql-endtime-timestamp/) , [Time Zone관련 spring boot 설정](https://www.baeldung.com/mysql-jdbc-timezone-spring-boot), [TIME ZONE](https://jwkim96.tistory.com/23)
- [x] #8

**Comment by General-code** [comment]
### 멘토님께 테이블 명세서와 ERD 첨삭을 요청드립니다.

- [Table 명세서](https://docs.google.com/spreadsheets/d/1rgGFkdOszaaKD-_4fSFO6unIKImuL7JJI026zKLDUzs/edit#gid=305865055)
- [ERD](https://www.erdcloud.com/d/SzGaQNfnrBpj4zauy)

- 설명 : 휠체어 충전 서비스를 지원하는 복지센터의 open API중 필요한 것만을 추려서 저장한 것이 WHEEL_CENTER 스키마 입니다. (OPEN API)를 DB에 저장할 생각입니다. 
- 각 센터에 대해 리뷰를 남길 수 있고 추천/비추천을 할 수 있습니다.
- 지도에서 가까운 위치에있는 곳을 찾아서 보내주는 기능을 구현해야 할 것 같습니다 
- 좋아하는 센터에 대해서 즐겨찾기 기능을 쓸 수 있습니다. 지도 API를 통해서 프런트 엔드에서 통신하도록 위도와 경도 센터 이름만 보내줄 예정입니다. 
- 밑에는 휠체어 충전 서비스 공공 API의 본문 예시입니다. ctprvnNm(도시명)과 sigungu(시군구)가 rdnmadr(도로명 주소) 안에 모두 들어있어서 지울지 말지 고민 중입니다.
 
```{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL_SERVICE",
            "type": "json"
        },
        "body": {
            "items": [
                {
                    "fcltyNm": "수서명화종합사회복지관",
                    "ctprvnNm": "서울특별시",
                    "signguNm": "강남구",
                    "signguCode": "11680",
                    "rdnmadr": "서울특별시 강남구 광평로51길 49",
                    "lnmadr": "서울특별시 강남구 수서동 707",
                    "latitude": "37.49213604",
                    "longitude": "127.0997527",
                    "instlLcDesc": "1층 주출입구 좌측 내부",
                    "weekdayOperOpenHhmm": "00:00",
                    "weekdayOperColseHhmm": "18:00",
                    "satOperOperOpenHhmm": "00:00",
                    "satOperCloseHhmm": "23:59",
                    "holidayOperOpenHhmm": "00:00",
                    "holidayCloseOpenHhmm": "23:59",
                    "smtmUseCo": "2",
                    "airInjectorYn": "N",
                    "moblphonChrstnYn": "Y",
                    "institutionNm": "수서명화종합사회복지관",
                    "institutionPhoneNumber": "02-459-2696",
                    "referenceDate": "2022-03-28",
                    "insttCode": "3220000"
                },
                {
                    "fcltyNm": "강남세움복지관",
                    "ctprvnNm": "서울특별시",
                    "signguNm": "강남구",
                    "signguCode": "11680",
                    "rdnmadr": "서울특별시 강남구 광평로60길 22",
                    "lnmadr": "서울특별시 강남구 수서동 721",
                    "latitude": "37.48698084",
                    "longitude": "127.106951",
                    "instlLcDesc": "1층 외부",
                    "weekdayOperOpenHhmm": "09:00",
                    "weekdayOperColseHhmm": "18:00",
                    "satOperOperOpenHhmm": "09:00",
                    "satOperCloseHhmm": "18:00",
                    "holidayOperOpenHhmm": "00:00",
                    "holidayCloseOpenHhmm": "23:59",
                    "smtmUseCo": "1",
                    "airInjectorYn": "N",
                    "moblphonChrstnYn": "N",
                    "institutionNm": "강남세움복지관",
                    "institutionPhoneNumber": "02-2184-8700",
                    "referenceDate": "2022-03-28",
                    "insttCode": "3220000"
                },
...]
            "totalCount": "3204",
            "numOfRows": "10",
            "pageNo": "1"
        }
    }
}

**Comment by Hyune-c** [comment]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/55722186/190309446-fa98fb5e-d5a6-4e2e-b005-3378de99fdb6.png">

- 적당한 규모인거 같아요. 좋습니다.
- 요즘은 테이블이나 컬럼명을 축약하지 않는 것 같아요.
    - Name, Nm 과 같이 일관성 없는 표현이 보입니다.
- 실무에서는 tinyInt 처럼 boolean 을 표현할 일은 별로 없는 것 같아요. 
    - 초기 설계 당시에는 yn 만 체크하면 될거라고 생각하지만 새로운 타입이 생기는 경우가 잦기 때문입니다.
- 테이블에 yn 플래그를 두는 것은 조금 옛날 방식입니다. 
    - 해당 row 가 상태를 가지고 있는 것이기 때문입니다. 하지만 나쁘지는 않습니다.
- 시간 타입 사용에 대해 좀 더 고민해주세요.
    - timezone 개념도 알아두시면 좋습니다.

**Comment by General-code** [comment]
- fctyName 같은 축약어들을 모두 풀어서 facultyName 등으로 변경했습니다.
- 그 외에도 다른 곳에서는 모두 번호나 핸드폰과 관련해서 phone이라고 표기되어 있는데 tel이라는 표현이 있어서 일관성 없는 tel을 phoneNumber로 바꿨습니다.

- airInjectorYn같은 경우는 open API 에서는 'Y' , 'N'로 반환 했지만 불리언 타입을 갖는 것이 맞다고 판단하여 불린 값으로 대체 했습니다. 
   - Yn대신 Flag라고 접미사를 붙였습니다. run time에 비교 연산을 쓰고 true 값을 반환 하는 것보다 미리 type converting하는 것이 비용적인 측면에서 낫기 때문입니다. 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/11516889/190656126-51e53543-3d0e-4fb4-abb9-bc1989f6057b.png">

**Comment by Hyune-c** [comment]
아직 몇 개 지적점이 보이긴 하지만 이쯤이면 초기 구현이 가능하실 것 같습니다.
이후는 코드에서 리뷰하겠습니다.

이 이슈는 이쯤에서 클로즈하고 `#8` 로 넘어가면 될거 같습니다.
